Back/admin area
Pefington/prairify.me pull request #78
Opened 2022-09-14 22:44 UTC by GregoryLAIGNEAU

2022-09-14 22:47 UTC, PierreAND approved these changes, later dismissed

2022-09-15 08:38 UTC, Samsou1 requested changes
Supprimer les admin helpers vides 
app/views/admin/dashboard/index.html.erb ==> il y a un bouton en commentaire, à supprimer ?

2022-09-15 11:05 UTC, Samsou1 submitted a review, later dismissed

2022-09-15 11:14 UTC, Pefington approved these changes

2022-09-15 11:16 UTC, PierreAND approved these changes

2022-09-15 11:21 UTC, merged